### ISSUE TITLE
SchedulerSystem getting stopped 

### ISSUE THREAD

**Issue by kumar-cherry** [PagerDuty/scheduler#42]
Hi Pagerduty Team,

I'm facing this after some days, scheduler system started and working what we expected, after some day it getting stoped, I need help to fix this issue,

2018-12-05 03:06:12 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
2018-12-05 03:07:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
**### 2018-12-05 03:07:43 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl trackResourceShutdown} - Shutting down SchedulingSystem...
2018-12-05 03:07:44 INFO  SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer initializeConsumerAndEnterPollLoop} - Stopping Kafka consumer.
2018-12-05 03:07:44 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl trackResourceShutdown} - Shutting down SchedulingSystem...
2018-12-05 03:07:45 ERROR SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer com$pagerduty$kafkaconsumer$SimpleKafkaConsumer$$backoffOnUnhandledExceptionLoop} - Fatal error in polling thread.
2018-12-05 03:07:45 INFO  SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer$$anon$1 run} - Shutting down polling thread.**
2018-12-05 03:07:45 INFO  AbstractCoordinator {org.apache.kafka.clients.consumer.internals.AbstractCoordinator markCoordinatorUnknown} - [Consumer clientId=consumer-1, groupId=scheduler] Group coordinator 10.200.1.91:9092 (id: 2147483645 rack: null) is unavailable or invalid, will attempt rediscovery
2018-12-05 03:07:45 INFO  AbstractCoordinator {org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler onSuccess} - [Consumer clientId=consumer-1, groupId=scheduler] Discovered group coordinator 10.200.1.91:9092 (id: 2147483645 rack: null)
2018-12-05 03:08:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
2018-12-05 03:09:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
2018-12-05 03:10:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
2018-12-05 03:11:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.
2018-12-05 03:12:13 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl$$anonfun$staleTasksGaugeSampleConsumer$1 apply$mcVI$sp} - Scheduler stale tasks result: 0 stale tasks.

**Comment by kumar-cherry** [comment]
@DWvanGeest I need help to fix this issue, thanks

**Comment by davidrusu** [comment]
It's not clear what the problem is here, from the logs you added it seems schedulers connection to your kafka cluster had a hiccup and scheduler was able to reconnect once the group coordinator connection was back up.

Were you seeing something other than what I described?

**Comment by kumar-cherry** [comment]
Hi @davidrusu Thanks for your valuable reply, 

1. In above mention log shows at time (2018-12-05 03:07:43) scheduler getting stopped, I don't known, what is the reason, after that I can able to see logs "Scheduler stale tasks result: 0 stale tasks" but scheduler consumer was not working, 

2. When I try to schedule Task via ScheduleClient , I'm getting following response - Succeeded,

2018-12-05 19:16:09 INFO  SchedulerClient {com.pagerduty.scheduler.LoggingSupport$$anonfun$reportFutureResults$2$$anonfun$apply$1 apply} - **Succeeded: enqueuing task to Kafka**: TaskKey(2018-12-05T14:18:00.943Z,8b0bd89d-204e-4980-a3ac-c9878c04317a,5d47e3ee-f326-4895-a5ce-26ef91dfe451).
2018-12-05 19:16:09 INFO  Scheduler$ {com.pagerduty.scheduler.LoggingSupport$$anonfun$reportFutureResults$1 apply} - **Attempting: sending tasks to scheduler**: List(TaskKey(2018-12-05T14:18:00.943Z,8b0bd89d-204e-4980-a3ac-c9878c04317a,5d47e3ee-f326-4895-a5ce-26ef91dfe451))
2018-12-05 19:16:09 INFO  Scheduler$ {com.pagerduty.scheduler.LoggingSupport$$anonfun$reportFutureResults$2$$anonfun$apply$1 apply} - **Succeeded: sending tasks to scheduler**: List(TaskKey(2018-12-05T14:18:00.943Z,8b0bd89d-204e-4980-a3ac-c9878c04317a,5d47e3ee-f326-4895-a5ce-26ef91dfe451))

3. Task Schedule says "Succeeded" but Not Stored in Cassandra "TaskSchedule" Table

Task getting scheduled in Kafka end but same task not available in Cassandra "TaskSchedule" table. I feel because of "SchedulerClient" stopped , when I restarted application  again it start working as expected ,task getting from Kafka and stored in Cassandra "TaskSchedule" table.

Any more information please ask and guide me,
thanks ,

**Comment by davidrusu** [comment]
Sounds like you have a theory as to what is happening, but this is something that would be hard to debug on our end as it may depend heavily on your specific environment and how your application is making use of the library. We haven't (to my knowledge) experienced something similar with our own services.

I'd encourage you to dig deeper to track down the root cause of this problem and submit a PR if you trace it back to the `scheduler` library. We don't have much capacity to help you debug this problem but the code is opensource so please do take advantage of that and poke around!

**Comment by kumar-cherry** [comment]
Hi @davidrusu , sorry for comment closed issue, 

After deep-drive looking Exception cases I hot following StackTrace, 

2018-12-06 10:12:33 INFO  SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer initializeConsumerAndEnterPollLoop} - Stopping Kafka consumer.
2018-12-06 10:12:33 INFO  Scheduler$ {com.pagerduty.scheduler.Scheduler$LoggingImpl trackResourceShutdown} - Shutting down SchedulingSystem...
2018-12-06 10:12:33 ERROR SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer com$pagerduty$kafkaconsumer$SimpleKafkaConsumer$$backoffOnUnhandledExceptionLoop} - Fatal error in polling thread.
java.lang.NoSuchMethodError: akka.actor.ActorSystem.shutdown()V
	at com.pagerduty.scheduler.akka.SchedulingSystem$$anonfun$shutdownAndWait$1.apply$mcV$sp(SchedulingSystem.scala:133) ~[time-engine.jar:na]
	at com.pagerduty.scheduler.Scheduler$LoggingImpl.trackResourceShutdown(Scheduler.scala:338) ~[time-engine.jar:na]
	at com.pagerduty.scheduler.akka.SchedulingSystem.shutdownAndWait(SchedulingSystem.scala:132) ~[time-engine.jar:na]
	at com.pagerduty.scheduler.SchedulerKafkaConsumer$$anonfun$shutdownResources$1.apply(SchedulerKafkaConsumer.scala:83) ~[time-engine.jar:na]
	at com.pagerduty.scheduler.SchedulerKafkaConsumer$$anonfun$shutdownResources$1.apply(SchedulerKafkaConsumer.scala:83) ~[time-engine.jar:na]
	at scala.util.Success.foreach(Try.scala:236) ~[time-engine.jar:na]
	at com.pagerduty.scheduler.SchedulerKafkaConsumer.shutdownResources(SchedulerKafkaConsumer.scala:83) ~[time-engine.jar:na]
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer.initializeConsumerAndEnterPollLoop(SimpleKafkaConsumer.scala:258) ~[time-engine.jar:na]
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer.com$pagerduty$kafkaconsumer$SimpleKafkaConsumer$$backoffOnUnhandledExceptionLoop(SimpleKafkaConsumer.scala:219) ~[time-engine.jar:na]
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer$$anon$1.run(SimpleKafkaConsumer.scala:127) [time-engine.jar:na]
2018-12-06 10:12:33 INFO  SchedulerKafkaConsumer {com.pagerduty.kafkaconsumer.SimpleKafkaConsumer$$anon$1 run} - Shutting down polling thread.
Exception in thread "TopicConsumer: scheduler [initializing]" java.lang.NoSuchMethodError: akka.actor.ActorSystem.shutdown()V
	at com.pagerduty.scheduler.akka.SchedulingSystem$$anonfun$shutdownAndWait$1.apply$mcV$sp(SchedulingSystem.scala:133)
	at com.pagerduty.scheduler.Scheduler$LoggingImpl.trackResourceShutdown(Scheduler.scala:338)
	at com.pagerduty.scheduler.akka.SchedulingSystem.shutdownAndWait(SchedulingSystem.scala:132)
	at com.pagerduty.scheduler.SchedulerKafkaConsumer$$anonfun$shutdownResources$1.apply(SchedulerKafkaConsumer.scala:83)
	at com.pagerduty.scheduler.SchedulerKafkaConsumer$$anonfun$shutdownResources$1.apply(SchedulerKafkaConsumer.scala:83)
	at scala.util.Success.foreach(Try.scala:236)
	at com.pagerduty.scheduler.SchedulerKafkaConsumer.shutdownResources(SchedulerKafkaConsumer.scala:83)
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer.initializeConsumerAndEnterPollLoop(SimpleKafkaConsumer.scala:258)
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer.com$pagerduty$kafkaconsumer$SimpleKafkaConsumer$$backoffOnUnhandledExceptionLoop(SimpleKafkaConsumer.scala:219)
	at com.pagerduty.kafkaconsumer.SimpleKafkaConsumer$$anon$1.run(SimpleKafkaConsumer.scala:127)

 thanks

**Comment by kumar-cherry** [comment]
Thanks This problem was resolved, This problem occur because of **Akka actor library version**.
